### PR TITLE
Working implementation of sas builder

### PR DESCRIPTION
**Pull request by wayeast**
Hello,  I just wanted to propose this as an incomplete implementation of the Azure shared authorization signature protocol.  This code only supports the latest version of the protocol, and only generates signed urls for blobs.  I use this code currently in a work project, and suppose that it should be relatively easy to expand to support files and tables if the idea is acceptable to you.

An example usage is included in the PR.

### CODE REVIEW

**Comment by MindFlavor** [comment]
That's fantastic!
I am working on the same topic but your implementation is much, *much* more elegant so I'll merge it immediately!
I will probably merge my implementation too even though is uglier since it takes a slightly different approach.

Thank you.

**Comment by MindFlavor** [comment]
This fixes https://github.com/MindFlavor/AzureSDKForRust/issues/147.

**Comment by wayeast** [comment]
:+1: thanks

**Comment by MindFlavor** [comment]
Well thank you! You did the work after all, I've just pushed a button! ;)

**Pull request merged**
